server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  prefix: /zhang
  ignored-services: springcloud-dept
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**

info:
  app.name: microservicecloud
  company.name: www.zouazoua.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

